version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
